name: "Terraform"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform-fmt:
    name: "Terraform Format"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Fmt
        run: terraform fmt -check -recursive -diff